
  CREATE OR REPLACE EDITIONABLE TRIGGER "MOBASHER"."TR_AUCTION_DELETE_REQUESTS" 
    BEFORE INSERT OR UPDATE
    ON AUCTION_DELETE_REQUESTS
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID IS NULL THEN
           :NEW.ID :=AUCTION_DELETE_REQUESTS_SEQ.NEXTVAL;
        END IF;
        :NEW.CREATED_DATE := SYSDATE;
        :NEW.CREATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
        :NEW.MODIFIED_DATE := SYSDATE;
        :NEW.MODIFIED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    ELSE
        :NEW.MODIFIED_DATE := SYSDATE;
        :NEW.MODIFIED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    END IF;
END TR_AUCTION_DELETE_REQUESTS;


/
ALTER TRIGGER "MOBASHER"."TR_AUCTION_DELETE_REQUESTS" ENABLE;