
  CREATE UNIQUE INDEX "MOBASHER"."BUYER_CHARGE_BALANCE_TRANS_ID_UNQ" ON "MOBASHER"."BUYER_CHARGE_BALANCE" ("TRANS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;