
  CREATE UNIQUE INDEX "MOBASHER"."MOBASHER_TASK_ASSIGNED_EMPLOYEE_PK" ON "MOBASHER"."MOBASHER_TASK_ASSIGNED_EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;