
  CREATE TABLE "MOBASHER"."AGENTS" 
   (	"ID" NUMBER, 
	"GROUP_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(225) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"WHATS" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"IS_SUPERVISOR" NUMBER, 
	"IS_ADMIN" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"IDENTITY_NUMBER" NUMBER NOT NULL ENABLE, 
	"BANK_ACCOUNT_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IBAN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BANK_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IDENTITY_URL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AGENT_TYPE_V2" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AGENT_TYPE" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;