
  CREATE TABLE "MOBASHER"."API_AUTHENTICATOR" 
   (	"ID" NUMBER, 
	"API_KEY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"API_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"GENERATED_DATE" DATE, 
	"EXPIRED_DATE" DATE, 
	"IS_USED" NUMBER DEFAULT 0, 
	 CONSTRAINT "API_AUTHENTICATOR_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;