
  CREATE TABLE "MOBASHER"."APP_NOTES" 
   (	"ID" NUMBER, 
	"APP_ID" NUMBER NOT NULL ENABLE, 
	"PAGE_ID" NUMBER NOT NULL ENABLE, 
	"OBJECT_ID" NUMBER, 
	"OPERATION_TYPE" NUMBER, 
	"NOTE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CATEGORY_ID" NUMBER, 
	"USER_ID" NUMBER, 
	 CONSTRAINT "APP_NOTES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;