
  CREATE TABLE "MOBASHER"."APP_DOCUMENTS" 
   (	"ID" NUMBER, 
	"OBJECT_TYPE" NUMBER, 
	"OBJECT_ID" NUMBER, 
	"MEDIA_TYPE" NUMBER, 
	"URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"FILE_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MIME_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NOTE_AR" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"NOTE_EN" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"DATA" CLOB COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;