
  CREATE TABLE "MOBASHER"."APP_APPLICATION_PRIVILEGES" 
   (	"ID" NUMBER, 
	"APPLICATION_ID" NUMBER NOT NULL ENABLE, 
	"DISPLAY_SEQUENCE" NUMBER NOT NULL ENABLE, 
	"ENTRY_TEXT" VARCHAR2(4000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PAGE_ID" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"LIST_ID" NUMBER, 
	"LIST_ENTRY_ID" NUMBER NOT NULL ENABLE, 
	"LIST_ENTRY_PARENT_ID" NUMBER, 
	"LAST_UPDATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_ON" DATE, 
	"ENTRY_IMAGE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"SHOW_IN_MENU_FLAG" CHAR(1) COLLATE "USING_NLS_COMP" DEFAULT 'Y' NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"AR_ENTRY_TEXT" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"CLEAR_CACHE_FLAG" CHAR(1) COLLATE "USING_NLS_COMP", 
	"CURRENT_LIST_ENTRY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "APP_APPLICATION_PRIVILEGES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;