
  CREATE TABLE "MOBASHER"."APP_ROLE_PRIVILEGES" 
   (	"ID" NUMBER, 
	"ROLE_ID" NUMBER, 
	"PRIVILEGE_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "APP_ROLE_PRIVILEGES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;