
  CREATE TABLE "MOBASHER"."AUCTION_INVOICES" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"AUCTION_ID" NUMBER, 
	"CURRENCY_ID" NUMBER, 
	"BUYER_BANK_TRANSFER_ID" NUMBER, 
	"SELLER_BANK_TRANSFER_ID" NUMBER, 
	"INFATH_BANK_TRANSFER_ID" NUMBER, 
	"AUCTION_GATE_BANK_TRANSFER_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NOTES_AR" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"NOTES_EN" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"INVOICE_TYPE_ID" NUMBER, 
	"PAYMENT_TYPE_ID" NUMBER, 
	"INVOICE_DATE" DATE, 
	"ADDITIONS" NUMBER, 
	"SUB_TOTAL" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"TOTAL_DISCOUNT" NUMBER, 
	"DISCOUNT_LABEL" NUMBER, 
	"TAX_PERCENTAGE" NUMBER, 
	"AUCTION_TYPE_ID" NUMBER, 
	"IS_PAYMENT_DONE" NUMBER, 
	"IS_REFUNDED" NUMBER, 
	"REFUNDED_DATE" DATE, 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "AUCTION_INVOICES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AUCTION_INVOICES_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "AUCTION_INVOICES_CURRENCY_FK" FOREIGN KEY ("AUCTION_GATE_BANK_TRANSFER_ID")
	  REFERENCES "MOBASHER"."AUCTION_GATE_BANK_TRANSFERS" ("ID") ENABLE, 
	 CONSTRAINT "AUCTION_INVOICES_AUCTION_GATE_BANK_TRANS_FK" FOREIGN KEY ("INFATH_BANK_TRANSFER_ID")
	  REFERENCES "MOBASHER"."INFATH_BANK_TRANSFERS" ("ID") ENABLE, 
	 CONSTRAINT "AUCTION_INVOICES_SELLER_BANK_TRANS_FK" FOREIGN KEY ("BUYER_BANK_TRANSFER_ID")
	  REFERENCES "MOBASHER"."BUYER_BANK_TRANSFERS" ("ID") ENABLE, 
	 CONSTRAINT "AUCTION_INVOICES_BUYER_BANK_TRANS_FK" FOREIGN KEY ("CURRENCY_ID")
	  REFERENCES "MOBASHER"."CURRENCY" ("ID") ENABLE, 
	 CONSTRAINT "AUCTION_INVOICES_INFATH_BANK_TRANS_FK" FOREIGN KEY ("SELLER_BANK_TRANSFER_ID")
	  REFERENCES "MOBASHER"."SELLER_BANK_TRANSFERS" ("ID") ENABLE, 
	 CONSTRAINT "AUCTION_INVOICES_BUYER_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;