
  CREATE TABLE "MOBASHER"."AUCTION_GATE_BANK_TRANSFERS" 
   (	"ID" NUMBER, 
	"BUYER_BANK_ACCOUNT_ID" NUMBER, 
	"SELLER_BANK_ACCOUNT_ID" NUMBER, 
	"MONEY_MOVEMENT_TYPE" NUMBER NOT NULL ENABLE, 
	"TRANSFER_DATE" DATE NOT NULL ENABLE, 
	"TOTAL_PRICE" NUMBER NOT NULL ENABLE, 
	"IS_ARRIVED" NUMBER DEFAULT 0, 
	"NOTES_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NOTES_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"RECEIPT_IMAGE_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "AUCTION_GATE_BANK_TRANSFER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AUCTION_GATE_BANK_TRANSFER_BUYER_BANK_ACCOUNT_FK" FOREIGN KEY ("BUYER_BANK_ACCOUNT_ID")
	  REFERENCES "MOBASHER"."BUYER_BANK_ACCOUNTS" ("ID") ENABLE, 
	 CONSTRAINT "AUCTION_GATE_BANK_TRANSFER_SELLER_BANK_ACCOUNT_FK" FOREIGN KEY ("SELLER_BANK_ACCOUNT_ID")
	  REFERENCES "MOBASHER"."SELLER_BANK_ACCOUNTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;