
  CREATE TABLE "MOBASHER"."AUCTION_DELETE_REQUESTS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"AUCTION_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PRODUCT_IDS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STATUS" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"REJECT_REASON" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"AUCTION_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"APPROVAL_LEVEL" NUMBER DEFAULT 0, 
	"IMAGE_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"MANAGER_REJECT_REASON" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"BIDS" NUMBER, 
	"PARTICIPANTS" NUMBER, 
	"AUCTIONS_COUNT" NUMBER, 
	"TYPE" NUMBER, 
	 CONSTRAINT "AUCTION_DELETE_REQUESTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AUCTION_DELETE_REQUESTS_APP_USERS_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOBASHER"."APP_USERS" ("ID") ENABLE, 
	 CONSTRAINT "AUCTION_DELETE_REQUESTS_SELLERS_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;