
  CREATE TABLE "MOBASHER"."AUCTION_INVOICE_DETAILS" 
   (	"ID" NUMBER, 
	"AUCTION_INVOICE_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PRICE" NUMBER, 
	"QUANTITY" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "AUCTION_INVOICE_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AUCTION_INVOICE_DETAILS_BUYER_FK" FOREIGN KEY ("AUCTION_INVOICE_ID")
	  REFERENCES "MOBASHER"."AUCTION_INVOICES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;