
  CREATE TABLE "MOBASHER"."BANKS" 
   (	"ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LOGO_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BANKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BANKS_FK" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "MOBASHER"."COUNTRIES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;