
  CREATE TABLE "MOBASHER"."BLACK_LIST" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"OBJECT_ID" NUMBER, 
	"OBJECT_TYPE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BLACK_LIST_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BLACK_LIST_NN" CHECK ( "BUYER_ID" IS NOT NULL ) ENABLE, 
	 CONSTRAINT "BLACK_LIST_OBJECT_ID_NN" CHECK ( "OBJECT_ID" IS NOT NULL ) ENABLE, 
	 CONSTRAINT "BLACK_LIST_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;