
  CREATE TABLE "MOBASHER"."BUGS_LINES" 
   (	"LINE_ID" NUMBER, 
	"BUG_ID" NUMBER, 
	"NOTE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"NOTE_TYPE" NUMBER, 
	"APPEAR_TYPE" NUMBER, 
	"STATUS" NUMBER, 
	"MIME_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FILE_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"REPLY_ID" NUMBER, 
	 PRIMARY KEY ("LINE_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;