
  CREATE TABLE "MOBASHER"."BUYER_IN_CLOSED_ENVELOPE" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"CLOSED_ENVELOPE_ID" NUMBER, 
	"INSURANCE_PAID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"WALLET_PAID" NUMBER, 
	"INSURANCE_REFUNDED" NUMBER DEFAULT 0, 
	"REFUNDED_DATE" DATE, 
	"WALLET_REFUNDED" NUMBER, 
	"INSURANCE_OWNER" NUMBER, 
	"INSURANCE_TYPE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_IN_CLOSED_ENVELOPE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_IN_CLOSED_ENVELOPE_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;