
  CREATE TABLE "MOBASHER"."BUYER_PACKAGE" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"BUYER_PERMISSION_GROUP" NUMBER, 
	"DURATION" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"END_IN" DATE, 
	"IS_END" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_PACKAGE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_PACKAGE_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;