
  CREATE TABLE "MOBASHER"."BUYER_CONFIRMATION_CODES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CODE" NUMBER, 
	"PHONE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"GENERATION_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"IS_USED" NUMBER DEFAULT 0, 
	"BUYER_TYPE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "BUYER_CONFIRMATION_CODES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;