
  CREATE TABLE "MOBASHER"."BUYER_ADDRESSES" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"CITY_ID" NUMBER, 
	"ADDRESS" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"POSTAL_CODE" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_ADDRESSES_COUNTRY_FK" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "MOBASHER"."COUNTRIES" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_ADDRESSES_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_ADDRESSES_CITY_FK" FOREIGN KEY ("CITY_ID")
	  REFERENCES "MOBASHER"."CITIES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;