
  CREATE TABLE "MOBASHER"."BUYER_TIMED_AUCTION_WATCHES" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"TIMED_AUCTION_ID" NUMBER, 
	 CONSTRAINT "BUYER_TIMED_AUCTION_WATCHES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;