
  CREATE TABLE "MOBASHER"."BUYER_SELLER_CONTACT" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"IS_BLOCKED" NUMBER DEFAULT 0, 
	"BLOCK_OWNER" NUMBER, 
	"IS_BUYER_SEND_NEW_MESSAGE" NUMBER DEFAULT 0, 
	"IS_SELLER_SEND_NEW_MESSAGE" NUMBER DEFAULT 0, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_SELLER_CONTACT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_SELLER_CONTACT_FK2" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_SELLER_CONTACT_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;