
  CREATE TABLE "MOBASHER"."BUYER_BANK_ACCOUNTS" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"BANK_ID" NUMBER, 
	"ACCOUNT_NO" NUMBER, 
	"ACCOUNT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"IBAN" NUMBER, 
	"IS_OWNER" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CURRENCY_ID" NUMBER, 
	"BANK_CARD_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_BANK_ACCOUNTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_BANK_ACCOUNTS_CURRENCY_FK" FOREIGN KEY ("CURRENCY_ID")
	  REFERENCES "MOBASHER"."CURRENCY" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_BANK_ACCOUNTS_BANK_FK" FOREIGN KEY ("BANK_ID")
	  REFERENCES "MOBASHER"."BANKS" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_BANK_ACCOUNTS_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;