
  CREATE TABLE "MOBASHER"."BUYER_EDAAT_INSURANCE" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"INVOICE_NO" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"EDAAT_STATUS_ID" NUMBER, 
	"INSURANCE_PRICE" NUMBER NOT NULL ENABLE, 
	"TOTAL_PRICE" NUMBER NOT NULL ENABLE, 
	"INTERNAL_CODE" NUMBER NOT NULL ENABLE, 
	"REFUND_STATUS_ID" NUMBER, 
	"IS_BALANCE_ADDED" NUMBER DEFAULT 0, 
	"EPTN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PAYMENT_DATE" DATE, 
	"REFUNDED_DATE" DATE, 
	"REFUNDED_OPTION_NO" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"REFUND_PRICE" NUMBER DEFAULT 0, 
	"REFUND_TO_ID" NUMBER, 
	"REFUND_NOTES" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"REFUND_REQUEST_DATE" DATE, 
	"BUYER_BANK_ACCOUNT" NUMBER, 
	"REFUND_INVOICE_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"EDAAT_INVOICES_REF" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"BUYER_TIMED_AUCTION_ID" NUMBER, 
	 CONSTRAINT "BUYER_EDAAT_INSURANCE_INVOICE_NO_UNQ" UNIQUE ("INVOICE_NO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_EDAAT_INSURANCE_INTERNAL_CODE_UNQ" UNIQUE ("INTERNAL_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_EDAAT_INSURANCE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_EDAAT_INSURANCE_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_EDAAT_INSURANCE_FK2" FOREIGN KEY ("BUYER_BANK_ACCOUNT")
	  REFERENCES "MOBASHER"."BUYER_BANK_ACCOUNTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;