
  CREATE TABLE "MOBASHER"."BUYER_VEHICLE_IMAGES" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"BUYER_VEHICLE_ID" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"IMAGE_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_VEHICLE_IMAGES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_VEHICLE_IMAGES_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_VEHICLE_IMAGES_FK2" FOREIGN KEY ("BUYER_VEHICLE_ID")
	  REFERENCES "MOBASHER"."BUYER_VEHICLE" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;