
  CREATE TABLE "MOBASHER"."BUYER_PERMISSION_GROUP" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"JOIN_TIMED_AUCTIONS" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"JOIN_LIVE_AUCTIONS" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"RECEIVE_NOTIFICATIONS" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CAN_AUTO_BID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CAN_JUMP_BID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"USE_WATCH_LIST" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"WATCH_LIST_COUNT" NUMBER DEFAULT 0, 
	"LIVE_AUCTION_CHAT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"GET_RELATED_PRODUCTS" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"GRACE_HOURS" NUMBER DEFAULT 0, 
	"ADD_PRODUCTS_NOTES" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PUBLISHED" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"THREE_MONTHS_FEES" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"SIX_MONTHS_FEES" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"TWELVE_MONTHS_FEES" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"IS_FEES" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"KEY" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"WALLET_CHARGE_FEES_DISCOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"SHOW_CHANCE_TO_WIN_PROGRESS_BAR" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_PERMISSION_GROUP_KEY_UNQ" UNIQUE ("KEY")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_PERMISSION_GROUP_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_PERMISSION_GROUP_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;