
  CREATE TABLE "MOBASHER"."BUYER_SELLER_CHAT" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"MESSAGE" VARCHAR2(500) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"IS_BUYER_SEEN" NUMBER DEFAULT 0, 
	"IS_SELLER_SEEN" NUMBER DEFAULT 0, 
	"SENDER_TYPE_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_SELLER_CHAT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_SELLER_CHAT_FK2" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_SELLER_CHAT_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;