
  CREATE TABLE "MOBASHER"."BUYER_SANAD" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"SANAD_ID" NUMBER NOT NULL ENABLE, 
	"SANAD_TYPE_ID" NUMBER, 
	"CURRENCY" NUMBER, 
	"TOTAL_VALUE" NUMBER NOT NULL ENABLE, 
	"STATUS_ID" NUMBER, 
	"BUYER_CHARGE_BALANCE" NUMBER, 
	"SANAD_NO" NUMBER, 
	"IS_BALANCE_ADDED" NUMBER DEFAULT 0, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_SANAD_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_SANAD_UNQ" UNIQUE ("SANAD_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_SANAD_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;