
  CREATE TABLE "MOBASHER"."BUYER_NOTIFICATIONS" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"TYPE_ID" NUMBER, 
	"MESSAGE_AR" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"MESSAGE_EN" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"IS_SEEN" NUMBER DEFAULT 0, 
	"IS_CANCELED" NUMBER DEFAULT 0, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_NOTIFICATION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_NOTIFICATION_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;