
  CREATE TABLE "MOBASHER"."BUYER_BANK_TRANSFERS" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"AUCTION_INVOICE_ID" NUMBER, 
	"BUYER_BANK_ACCOUNT_ID" NUMBER, 
	"SELLER_BANK_ACCOUNT_ID" NUMBER, 
	"MONEY_MOVEMENT_TYPE" NUMBER NOT NULL ENABLE, 
	"TRANSFER_DATE" DATE NOT NULL ENABLE, 
	"TOTAL_PRICE" NUMBER NOT NULL ENABLE, 
	"IS_ARRIVED" NUMBER DEFAULT 0, 
	"IS_REFUNDED" NUMBER DEFAULT 0, 
	"REFUND_DATE" DATE, 
	"NOTES" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"RECEIPT_IMAGE_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"AUCTIONS_GATE_BANK_ACCOUNT" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_BANK_TRANSFERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_BANK_TRANSFERS_SELLER_BANK_ACC_FK" FOREIGN KEY ("SELLER_BANK_ACCOUNT_ID")
	  REFERENCES "MOBASHER"."SELLER_BANK_ACCOUNTS" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_BANK_TRANSFERS_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_BANK_TRANSFERS_BUYER_BANK_ACC_FK" FOREIGN KEY ("BUYER_BANK_ACCOUNT_ID")
	  REFERENCES "MOBASHER"."BUYER_BANK_ACCOUNTS" ("ID") ENABLE, 
	 CONSTRAINT "BUYER_BANK_TRANSFERS_AUCTION_INVOICE_FK" FOREIGN KEY ("AUCTION_INVOICE_ID")
	  REFERENCES "MOBASHER"."AUCTION_INVOICES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;