
  CREATE TABLE "MOBASHER"."BUYER_VISITED_AUCTION_CONTAINERS" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"AUCTION_CONTAINER_ID" NUMBER, 
	 CONSTRAINT "BUYER_VISITED_AUCTION_CONTAINERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;