
  CREATE TABLE "MOBASHER"."BUYER_ADDRESS_REQUESTS" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"BUYER_NID" NUMBER, 
	"BUYER_NAME" VARCHAR2(555) COLLATE "USING_NLS_COMP", 
	"BUYER_PHONE" VARCHAR2(555) COLLATE "USING_NLS_COMP", 
	"BUYER_EMAIL" VARCHAR2(555) COLLATE "USING_NLS_COMP", 
	"COUNRTY_ID" NUMBER, 
	"CITY_ID" NUMBER, 
	"POSTAL_CODE" VARCHAR2(555) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(555) COLLATE "USING_NLS_COMP", 
	"ADDRESS_URL" VARCHAR2(555) COLLATE "USING_NLS_COMP", 
	"IS_AUCTION_WINER" NUMBER, 
	"IS_AUCTION_BIDER" NUMBER, 
	"IS_AUCTION_PARTICIPANT" NUMBER, 
	"IS_ACTIVE" NUMBER, 
	"STATUS" NUMBER, 
	"REJECT_REASON" VARCHAR2(555) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "BUYER_ADDRESS_REQUESTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;