
  CREATE TABLE "MOBASHER"."BUYER_IN_TIMED_AUCTION" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"TIMED_AUCTION_ID" NUMBER, 
	"IS_INSURANCE_PAID" NUMBER, 
	"WALLET_PAID_ID" NUMBER, 
	"INSURANCE_REFUNDED" NUMBER, 
	"REFUNDED_DATE" DATE, 
	"WALLET_REFUNDED_ID" NUMBER, 
	"INSURANCE_OWNER_ID" NUMBER, 
	"INSURANCE_TYPE_ID" NUMBER, 
	"INSURANCE_DELIVERED" NUMBER, 
	"IS_INSURANCE_DELIVERED_PAID" NUMBER, 
	"INSURANCE_DELIVERED_PAID_WALLET_ID" NUMBER, 
	"IS_INSURANCE_DELIVERED_REFUNDED" NUMBER, 
	"INSURANCE_DELIVERED_REFUNDED_WALLET_ID" NUMBER, 
	"PARTICIPANT_AS_ID" NUMBER, 
	"DOCUMENTS" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"IS_WINNER" NUMBER, 
	"IS_CURRENT_AUCTION" NUMBER, 
	 CONSTRAINT "BUYERS_IN_TIMED_AUCTION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYERS_IN_TIMED_AUCTION_TIMED_DELIVERED_REFUNDED_WALLET_FK" FOREIGN KEY ("INSURANCE_DELIVERED_REFUNDED_WALLET_ID")
	  REFERENCES "MOBASHER"."WALLETS" ("ID") ENABLE, 
	 CONSTRAINT "BUYERS_IN_TIMED_AUCTION_BUYER_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE, 
	 CONSTRAINT "BUYERS_IN_TIMED_AUCTION_TIMED_DELIVERED_PAID_WALLET_FK" FOREIGN KEY ("INSURANCE_DELIVERED_PAID_WALLET_ID")
	  REFERENCES "MOBASHER"."WALLETS" ("ID") ENABLE, 
	 CONSTRAINT "BUYERS_IN_TIMED_AUCTION_TIMED_PAID_WALLET_FK" FOREIGN KEY ("WALLET_PAID_ID")
	  REFERENCES "MOBASHER"."WALLETS" ("ID") ENABLE, 
	 CONSTRAINT "BUYERS_IN_TIMED_AUCTION_TIMED_REFUNDED_WALLET_FK" FOREIGN KEY ("WALLET_REFUNDED_ID")
	  REFERENCES "MOBASHER"."WALLETS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;