
  CREATE TABLE "MOBASHER"."BUYER_CHARGE_BALANCE" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"TOTAL_AMOUNT" NUMBER NOT NULL ENABLE, 
	"TRACK_ID" NUMBER NOT NULL ENABLE, 
	"BUYER_SANAD" NUMBER, 
	"CHARGE_BALANCE_FEES" NUMBER NOT NULL ENABLE, 
	"WALLET_CHARGE_FEES_DISCOUNT" NUMBER DEFAULT 0, 
	"TRANS_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "BUYER_CHARGE_BALANCE_TRANS_ID_UNQ" UNIQUE ("TRANS_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_CHARGE_BALANCE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_CHARGE_BALANCE_TRACK_ID_UNQ" UNIQUE ("TRACK_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BUYER_CHARGE_BALANCE_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;