
  CREATE TABLE "MOBASHER"."CITIES" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"COUNTRY_ID" NUMBER, 
	"HAVE_VEHICLES_PARTNERS" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "CITIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CITIES_FK" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "MOBASHER"."COUNTRIES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;