
  CREATE TABLE "MOBASHER"."CITIES_COLLECTION" 
   (	"ID" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATED_ON" TIMESTAMP (6) DEFAULT sys_extract_utc(SYSTIMESTAMP) NOT NULL ENABLE, 
	"LAST_MODIFIED" TIMESTAMP (6) DEFAULT sys_extract_utc(SYSTIMESTAMP) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"JSON_DOCUMENT" BLOB, 
	 CHECK ("JSON_DOCUMENT" is json format oson (size limit 32m)) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;