
  CREATE TABLE "MOBASHER"."COMPANIES" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(225) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(225) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION_AR" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION_EN" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"WHATS" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LOGO_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "COMPANIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;