
  CREATE TABLE "MOBASHER"."CONTACT_RECORD" 
   (	"ID" NUMBER, 
	"OBJECT_ID" NUMBER, 
	"OBJECT_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CONTACT_TEXT" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"NOTES" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CONTACT_DATE" DATE, 
	"CONTACT_TIME" TIMESTAMP (6), 
	"STATUS" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"INFATH_REPORT_ID" NUMBER, 
	"WRONG_NUMBER" NUMBER, 
	"ATTACHED_URL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	 CONSTRAINT "CONTACT_RECORD_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CONTACT_RECORD_FK" FOREIGN KEY ("INFATH_REPORT_ID")
	  REFERENCES "MOBASHER"."INFATH_DECISION" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;