
  CREATE TABLE "MOBASHER"."COUNTRIES" 
   (	"ID" NUMBER, 
	"KEY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CURRENCY_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "COUNTRIES_FK2" FOREIGN KEY ("CURRENCY_ID")
	  REFERENCES "MOBASHER"."CURRENCY" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;