
  CREATE TABLE "MOBASHER"."CURRENCY" 
   (	"ID" NUMBER, 
	"KEY" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PERCENTAGE_TO_LOCAL_CURRENCY" NUMBER, 
	"IS_DEFAULT" NUMBER DEFAULT 0, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "CURRENCY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;