
  CREATE TABLE "MOBASHER"."EDAAT_PAYMENT_INVOICES" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"EDAAT_INVOICE_REF_ID" NUMBER, 
	"AUCTION_INVOICE_ID" NUMBER, 
	"INVOICE_NO" NUMBER, 
	"EDAAT_STATUS" NUMBER, 
	"PRICE" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"INTERNAL_CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EPTN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PAYMENT_DATE" DATE, 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "EDAAT_PAYMENT_INVOICES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EDAAT_PAYMENT_INVOICES_BUYER_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE, 
	 CONSTRAINT "EDAAT_PAYMENT_INVOICES_EDAAT_INVOICE_REF_FK" FOREIGN KEY ("EDAAT_INVOICE_REF_ID")
	  REFERENCES "MOBASHER"."EDAAT_INVOICES_REF" ("ID") ENABLE, 
	 CONSTRAINT "EDAAT_PAYMENT_INVOICES_AUCTION_INVOICE_FK" FOREIGN KEY ("AUCTION_INVOICE_ID")
	  REFERENCES "MOBASHER"."AUCTION_INVOICES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;