
  CREATE TABLE "MOBASHER"."EDAAT_INVOICES_REF" 
   (	"ID" NUMBER, 
	"INVOICE_NO" NUMBER, 
	"TYPE_ID" NUMBER, 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "EDAAT_INVOICES_REF_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;