
  CREATE TABLE "MOBASHER"."EFAA_LOGS" 
   (	"ID" NUMBER, 
	"BILL_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SADAD_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"REQUEST_BODY" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"RESPONSE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"MESSAGE" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"CALLBACK_STATUS" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;