
  CREATE TABLE "MOBASHER"."EMPLOYEES" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"USER_TYPE_ID" NUMBER, 
	"IDENTITY_TYPE_ID" NUMBER, 
	"IDENTITY_NUMBER" NUMBER, 
	"JOB" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"JOB_NO" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"COUNTRY_CALL_KEY" VARCHAR2(25) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AVATAR_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"IS_ADMIN" NUMBER DEFAULT 0, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"USER_ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"SELLER_ADMIN" NUMBER, 
	"IS_MANAGER" NUMBER, 
	"AUTHORIZATION_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"ID_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "EMPLOYEES_CON_EMIAL" UNIQUE ("EMAIL")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EMPLOYEES_NID_10DEGITS" CHECK (LENGTH(IDENTITY_NUMBER) = 10) DISABLE, 
	 CONSTRAINT "EMPLOYEES_NID_UNQ" UNIQUE ("IDENTITY_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EMPLOYEES_PHONE_UNQ" UNIQUE ("PHONE") DISABLE, 
	 CONSTRAINT "EMPLOYEES_NID_CHECK" CHECK ( "IDENTITY_NUMBER" IS NOT NULL ) ENABLE, 
	 CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EMPLOYEES_PHONE_9DEGITS" CHECK (LENGTH(PHONE) = 9) DISABLE, 
	 CONSTRAINT "EMPLOYEES_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOBASHER"."APP_USERS" ("ID") ENABLE, 
	 CONSTRAINT "EMPLOYEES_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;