
  CREATE TABLE "MOBASHER"."ENVIRONMENT_SETTING" 
   (	"ID" NUMBER, 
	"PROVIDER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BASE_URL" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"AUTHERIZATION_TOKEN" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"AUTHERIZATION_TOKEN_EXPIRY_DATE" DATE, 
	"CLIENT_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CLIENT_SECRET" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"ENTITY_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"TEST_BASE_URL" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"TEST_CLIENT_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TEST_CLIENT_SECRET" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"API_KEY" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"TEST_API_KEY" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;