
  CREATE TABLE "MOBASHER"."ERROR_LOGS" 
   (	"ID" NUMBER, 
	"ERROR_CODE" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"ERROR_DATE" DATE, 
	"PROCESS_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ERROR_TYPE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"OBJECT_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LOGGER_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"OBJECT_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ERR_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "ERROR_LOGS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;