
  CREATE TABLE "MOBASHER"."EXTRA_EXPENSES_IN_TIMED_AUCTION" 
   (	"ID" NUMBER, 
	"PRODUCT_IN_TIMED_AUCTION_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"VALUE" NUMBER, 
	"TYPE_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"SELLER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"AUCTION_ID" NUMBER, 
	 CONSTRAINT "EXTRA_EXPENSES_IN_TIMED_AUCTION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;