
  CREATE TABLE "MOBASHER"."FINANCE_REVIEW_PRODUCTS" 
   (	"ID" NUMBER, 
	"AUCTION_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "FINANCE_REVIEW_PRODUCTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;