
  CREATE TABLE "MOBASHER"."HORSE_DETAILS" 
   (	"ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"HORSE_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"HORSE_COLOR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"HORSE_GENDER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FATHER_NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FATHER_NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MOTHER_NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MOTHER_NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AGE_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AGE_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"HEIGHT_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"HEIGHT_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "HORSE_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;