
  CREATE TABLE "MOBASHER"."IAM_LOGS" 
   (	"ID" NUMBER, 
	"CLIENT_ID" NUMBER, 
	"LOGIN_METHOD" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SESSION_NO" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"REQUEST_BODY" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"RESPONSE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"TRANS_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"RANDOM" NUMBER, 
	"MESSAGE" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"TRACE_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CLIENT_ID_NO" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;