
  CREATE TABLE "MOBASHER"."IAM_CALLBACK" 
   (	"ID" NUMBER, 
	"CALLBACK_BODY" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"STATUS" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"IAM_STATUS" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;