
  CREATE TABLE "MOBASHER"."INDIVIDUAL_REALESTATE_ATTACHMENTS" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_ATTACHMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_ATTACHMENTS_FK" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "MOBASHER"."INDIVIDUAL_REALESTATE_REQUESTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;