
  CREATE TABLE "MOBASHER"."INDIVIDUAL_REALESTATE_AFTER_ASSIGNED" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"MARKETING_CONTRACT_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"ASSIGNED_MARKETING_CONTRACT_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"MEDIATION_CONTRACT_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"AUCTION_REQUEST_FORM_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"RECEIVED_PAYMENT_FORM_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"AUCTION_CLOSING_FORM_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_AFTER_ASSIGNED_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_AFTER_ASSIGNED_FK" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "MOBASHER"."INDIVIDUAL_REALESTATE_REQUESTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;