
  CREATE TABLE "MOBASHER"."INDIVIDUAL_PORTABLE_CHAT" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"MESSAGE" VARCHAR2(2555) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_SEEN" NUMBER DEFAULT 0, 
	 CONSTRAINT "INDIVIDUAL_PORTABLE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;