
  CREATE TABLE "MOBASHER"."INDIVIDUAL_REALESTATE_DECLINED_REQUESTS" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"DECLINED_REASON" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_DECLINED_REQUESTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_DECLINED_REQUESTS_REALESTATE_REQUESTS_FK" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "MOBASHER"."INDIVIDUAL_REALESTATE_REQUESTS" ("ID") ENABLE, 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_DECLINED_REQUESTS_SELLERS_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;