
  CREATE TABLE "MOBASHER"."INDIVIDUAL_REALESTATE_SELLER_CHAT" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"MESSAGE" VARCHAR2(2555) COLLATE "USING_NLS_COMP", 
	"SELLER_ID" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_SEEN" NUMBER DEFAULT 0, 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_SELLER_CHAT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_REQUESTS_FK" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "MOBASHER"."INDIVIDUAL_REALESTATE_REQUESTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;