
  CREATE TABLE "MOBASHER"."INDIVIDUAL_PORTABLE_PRICE_HISTORY" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"OLD_PRICE" NUMBER, 
	"SUGGESTED_PRICE" NUMBER, 
	"SUGGEST_REASON" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"HAS_BUYER_CONFIRMED" NUMBER DEFAULT 2, 
	 CONSTRAINT "INDIVIDUAL_PORTABLE_SUGGESTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;