
  CREATE TABLE "MOBASHER"."INDIVIDUAL_PORTABLE_SOLD" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"INVOICE_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TRANSFER_OWNERSHIP_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "INDIVIDUAL_PORTABLE_SOLD_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INDIVIDUAL_PORTABLE_SOLD_PRODUCT_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "MOBASHER"."PRODUCTS" ("ID") DISABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;