
  CREATE TABLE "MOBASHER"."INDIVIDUAL_PORTABLE_OFFER" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MINIMUM_ACCEPTABLE_PRICE" NUMBER, 
	"OFFER_PRICE" NUMBER, 
	"IS_ACCEPTED" NUMBER DEFAULT 0, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"OFFER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"STATUS" NUMBER, 
	"REJECT_REASON" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"BUYER_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BUYER_PHONE" NUMBER, 
	"BUYER_NATIONAL_ID" NUMBER, 
	 CONSTRAINT "INDIVIDUAL_PORTABLE_OFFER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INDIVIDUAL_PORTABLE_OFFER_PRODUCT_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "MOBASHER"."PRODUCTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;