
  CREATE TABLE "MOBASHER"."INDIVIDUAL_REALESTATE_EVALUATED_REQUESTS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"EVALUATOR_USER_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"BUYER_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BUYER_PHONE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CITY" NUMBER, 
	"PROPERTY_TYPE" NUMBER, 
	"SUB_CATEGORY" NUMBER, 
	"INSTRUMENT_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SPACE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PROPERTY_PRICE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NOTES" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MAP_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CONSTRUCTION_LICENSE_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"INSTRUMENT_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"CADASTRAL_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"EVALUATION_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"IS_EVALUATED" NUMBER DEFAULT 0, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "INDIVIDUAL_REALESTATE_EVALUATED_REQUESTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;