
  CREATE TABLE "MOBASHER"."INFATH_EMPLOYEES" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"USER_TYPE_ID" NUMBER, 
	"IDENTITY_TYPE_ID" NUMBER, 
	"IDENTITY_NUMBER" NUMBER, 
	"JOB" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"JOB_NO" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"COUNTRY_CALL_KEY" VARCHAR2(25) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AVATAR_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"RESET_TOKEN" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"RESET_TOKEN_EXPIRY" NUMBER, 
	"IS_ADMIN" NUMBER DEFAULT 0, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "INFATH_EMPLOYEES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INFATH_EMPLOYEES_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOBASHER"."APP_USERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;