
  CREATE TABLE "MOBASHER"."INFATH_EXECUTIVE_BOND" 
   (	"ID" NUMBER, 
	"BOND_NUMBER" NUMBER, 
	"BOND_RATING" NUMBER, 
	"BOND_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BOND_SOURCE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EXECUTION_SEAL_NUMBER" NUMBER, 
	"AMOUNT_CLAIMED" NUMBER, 
	"BOND_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"INFATH_REPORT_ID" NUMBER, 
	 CONSTRAINT "EXECUTIVE_BOND_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INFATH_EXECUTIVE_BOND_FK" FOREIGN KEY ("INFATH_REPORT_ID")
	  REFERENCES "MOBASHER"."INFATH_DECISION" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;