
  CREATE TABLE "MOBASHER"."INFATH_DECISION_REQUESTER" 
   (	"ID" NUMBER, 
	"DECISION_ID" NUMBER, 
	"REQUESTER_ID" NUMBER, 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "INFATH_DECISION_REQUESTER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INFATH_DECISION_REQUESTER_FK2" FOREIGN KEY ("REQUESTER_ID")
	  REFERENCES "MOBASHER"."INFATH_EXECUTION_REQUESTER" ("ID") ENABLE, 
	 CONSTRAINT "INFATH_DECISION_REQUESTER_FK" FOREIGN KEY ("DECISION_ID")
	  REFERENCES "MOBASHER"."INFATH_DECISION" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;