
  CREATE TABLE "MOBASHER"."INFATH_PROSECUTION_TYPE" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PROSECUTION_NUMBER" NUMBER, 
	"PROSECUTION_SOURCE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PROSECUTION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"INFATH_REPORT_ID" NUMBER, 
	 CONSTRAINT "PROSECUTION_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INFATH_PROSECUTION_TYPE_FK" FOREIGN KEY ("INFATH_REPORT_ID")
	  REFERENCES "MOBASHER"."INFATH_DECISION" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;