
  CREATE TABLE "MOBASHER"."INFATH_APP_ROLES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ROLE_DESCRIPTION" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"ACTIVE_FLAG" VARCHAR2(1) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"ROLE_GROUP_ID" NUMBER, 
	 CONSTRAINT "INFATH_APP_ROLES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;