
  CREATE TABLE "MOBASHER"."INFATH_DECISION" 
   (	"ID" NUMBER, 
	"REPORT_NUMBER" NUMBER, 
	"REQUEST_NUMBER" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER, 
	"FILE_ID" NUMBER, 
	 CONSTRAINT "INFATH_REPORT_UNQ_1" UNIQUE ("REPORT_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INFATH_REPORT_UNQ_2" UNIQUE ("REQUEST_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INFATH_REPORT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INFATH_DECISION_FILE_FK" FOREIGN KEY ("FILE_ID")
	  REFERENCES "MOBASHER"."INFATH_UPLOAD_REPORT" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;