
  CREATE TABLE "MOBASHER"."INFATH_DEPUTY_EXECUTION_REQUESTER" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NATIONALITY_ID" NUMBER, 
	"IDENTITY_NUMBER" NUMBER, 
	"IDENTITY_TYPE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER, 
	 CONSTRAINT "DEPUTY_EXECUTION_REQUESTER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;