
  CREATE TABLE "MOBASHER"."INFATH_UPLOAD_REPORT" 
   (	"ID" NUMBER, 
	"REPORT_NUMBER" NUMBER, 
	"MISSION_NUMBER" NUMBER, 
	"REPORT_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"NOTES" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"STATUS" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER, 
	"IS_DISPLAYED" NUMBER, 
	"FILE_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "INFATH_UPLOAD_REPORT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INFATH_UPLOAD_REPORT_UNQ" UNIQUE ("REPORT_NUMBER")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;