
  CREATE TABLE "MOBASHER"."INFATH_EXECUTED_AGAINST" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NATIONALITY_ID" NUMBER, 
	"IDENTITY_NUMBER" NUMBER, 
	"IDENTITY_TYPE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER, 
	 CONSTRAINT "INFATH_EXECUTED_AGAINST_UNQ" UNIQUE ("IDENTITY_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EXECUTED_AGAINST_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;