
  CREATE TABLE "MOBASHER"."INFATH_DECISION_AGAINST" 
   (	"ID" NUMBER, 
	"DECISION_ID" NUMBER, 
	"AGAINST_ID" NUMBER, 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "INFATH_DECISION_AGAINST_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INFATH_DECISION_AGAINST_FK" FOREIGN KEY ("DECISION_ID")
	  REFERENCES "MOBASHER"."INFATH_DECISION" ("ID") ENABLE, 
	 CONSTRAINT "INFATH_DECISION_AGAINST_FK2" FOREIGN KEY ("AGAINST_ID")
	  REFERENCES "MOBASHER"."INFATH_EXECUTED_AGAINST" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;