
  CREATE TABLE "MOBASHER"."LAGNET_BEA" 
   (	"ID" NUMBER, 
	"JOB" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"INFATH_EMPLOYEE_ID" NUMBER, 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"AUCTION_ID" NUMBER, 
	 CONSTRAINT "LAGNET_BEA_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LAGNET_BEA_FK" FOREIGN KEY ("INFATH_EMPLOYEE_ID")
	  REFERENCES "MOBASHER"."INFATH_EMPLOYEES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;