
  CREATE TABLE "MOBASHER"."LOOKUP_BASE" 
   (	"ID" NUMBER, 
	"CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LINKED_ID" NUMBER, 
	"IS_ACTIVE" NUMBER, 
	"DESCRIPTION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "LOOKUP_BASE_PK" PRIMARY KEY ("ID") DISABLE, 
	 CONSTRAINT "LOOKUP_BASE_UNQ" UNIQUE ("CODE") DISABLE, 
	 CONSTRAINT "LOOKUP_BASE_FK" FOREIGN KEY ("LINKED_ID")
	  REFERENCES "MOBASHER"."LOOKUP_BASE" ("ID") DISABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;