
  CREATE TABLE "MOBASHER"."LOOKUP_DETAIL" 
   (	"ID" NUMBER, 
	"SEQ" NUMBER, 
	"CODE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"NAME_AR" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"LINKED_LOOKUP_ID" NUMBER NOT NULL ENABLE, 
	"LINKED_DETAIL_ID" NUMBER, 
	"IS_ACTIVE" NUMBER, 
	"CLASSES" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ICON" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"COLOR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IMAGE_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"BACKGROUND_COLOR" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "LOOKUP_DETAIL_UNQ" UNIQUE ("CODE", "LINKED_LOOKUP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LOOKUP_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LOOKUP_DETAIL_FK2" FOREIGN KEY ("LINKED_DETAIL_ID")
	  REFERENCES "MOBASHER"."LOOKUP_DETAIL" ("ID") DISABLE, 
	 CONSTRAINT "LOOKUP_DETAIL_FK1" FOREIGN KEY ("LINKED_LOOKUP_ID")
	  REFERENCES "MOBASHER"."LOOKUP_BASE" ("ID") DISABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;