
  CREATE TABLE "MOBASHER"."MOBASHER_TASK_ATTACHEMENTS" 
   (	"ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"FILE_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FILE_SIZE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MIME_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "MOBASHER_TASK_ATTACHEMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MOBASHER_TASK_ATTACHEMENTS_FK1" FOREIGN KEY ("TASK_ID")
	  REFERENCES "MOBASHER"."MOBASHER_TASKS" ("ID") DISABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;