
  CREATE TABLE "MOBASHER"."MOBASHER_TASK_ASSIGNED_EMPLOYEE" 
   (	"ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "MOBASHER_TASK_ASSIGNED_EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MOBASHER_TASK_ASSIGNED_EMPLOYEE_FK2" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "MOBASHER"."MOBASHER_DEPARTMENTS" ("ID") ENABLE, 
	 CONSTRAINT "MOBASHER_TASK_ASSIGNED_EMPLOYEE_FK1" FOREIGN KEY ("TASK_ID")
	  REFERENCES "MOBASHER"."MOBASHER_TASKS" ("ID") ENABLE, 
	 CONSTRAINT "MOBASHER_TASK_ASSIGNED_EMPLOYEE_FK3" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "MOBASHER"."MOBASHER_EMPLOYEES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;