
  CREATE TABLE "MOBASHER"."MOBASHER_DEPARTMENTS" 
   (	"ID" NUMBER, 
	"SEQUENCE" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "MOBASHER_DEPARTMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;