
  CREATE TABLE "MOBASHER"."MOBASHER_TASKS" 
   (	"ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"STATUS_ID" NUMBER, 
	"PRIORITY_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"NOTES" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"PROGRESS" NUMBER DEFAULT 1, 
	"SUSPEND_NOTES" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"PROGRESS_DETAILS" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "MOBASHER_TASKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MOBASHER_TASKS_FK1" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "MOBASHER"."MOBASHER_DEPARTMENTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;