
  CREATE TABLE "MOBASHER"."MOBASHER_EMPLOYEES" 
   (	"ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"JOB" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"USER_ID" NUMBER, 
	"USER_TYPE_ID" NUMBER, 
	"IS_ADMIN" NUMBER DEFAULT 0, 
	"NID_TYPE_ID" NUMBER, 
	"NID" NUMBER, 
	"PHONE" NUMBER, 
	"EMAIL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_MANAGER" NUMBER DEFAULT 0, 
	"AVATAR_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP" DEFAULT 'https://objectstorage.me-jeddah-1.oraclecloud.<AWS_SECRET>KLtext/plain', 
	 CONSTRAINT "MOBASHER_EMPLOYEES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MOBASHER_EMPLOYEES_FK" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "MOBASHER"."MOBASHER_DEPARTMENTS" ("ID") ENABLE, 
	 CONSTRAINT "MOBASHER_EMPLOYEES_USERS_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOBASHER"."APP_USERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;