
  CREATE TABLE "MOBASHER"."NAFITH_TRANSACTIONS" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"AUCTION_ID" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"AUCTION_TYPE" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"MONEY_MOVEMENT_TYPE" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"ADDITIONS" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"TOTAL_PRICE" NUMBER, 
	"CURRENT_BALANCE" NUMBER, 
	"INSURANCE_TYPE" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"USED_FOR" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"BUYER" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "NAFITH_TRANSACTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;