
  CREATE TABLE "MOBASHER"."NEIGHBOURHOODS" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CITY_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "NEIGHBOURHOOD_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "NEIGHBOURHOOD_FK" FOREIGN KEY ("CITY_ID")
	  REFERENCES "MOBASHER"."CITIES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;