
  CREATE TABLE "MOBASHER"."PRODUCTS_VIEWS" 
   (	"ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"AUCTION_ID" NUMBER, 
	"AUCTION_TYPE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "PRODUCTS_VIEWS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;