
  CREATE TABLE "MOBASHER"."PRODUCT_IMAGES" 
   (	"ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"FILE_EXTENSION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FILE_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FILE_SIZE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MIME_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SEQ" NUMBER, 
	 CONSTRAINT "PRODUCT_IMAGES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;