
  CREATE TABLE "MOBASHER"."PRODUCT_IN_LIVE_AUCTION" 
   (	"ID" NUMBER, 
	"LANE_NO" NUMBER, 
	"STATUS" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PRODUCT_ID" NUMBER, 
	"INSURANCE" NUMBER, 
	"CREATED_AT" DATE, 
	"CREATED_BY" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"START_PRICE" NUMBER, 
	"TERMS_AR" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"INFATH_PRICE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"LIVE_AUCTION_ID" NUMBER, 
	"INFATH_RESULT" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"ANNOUNCEMENTS" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"BIDDING_STATUS_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ALLOW_SELL_PRICE" NUMBER, 
	"CURRENT_EVERY_CLICK" NUMBER, 
	"INFATH_RESULT_STATUS_ID" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"LIVE_AUCTION_SOLD_DETAIL_ID" NUMBER, 
	"LIVE_AUCTION_OFFER_DETAIL_ID" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"LIVE_AUCTION_DELIVERED_DETAIL_ID" NUMBER, 
	"TERMS_EN" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "PRODUCT_IN_LIVE_AUCTION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;