
  CREATE TABLE "MOBASHER"."PROPERTY_DIMENSIONS" 
   (	"ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"FACADE_ID" NUMBER, 
	"DESCRIPTION_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "PROPERTY_DIMENSIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;