
  CREATE TABLE "MOBASHER"."REGA_BORDERS" 
   (	"ID" NUMBER, 
	"NORTH_LIMIT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NORTH_LIMIT_DESCRIPTION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NORTH_LIMIT_LENGTHCHAR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EAST_LIMIT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EAST_LIMIT_DESCRIPTION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EAST_LIMIT_LENGTHCHAR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"WEST_LIMIT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"WEST_LIMIT_DESCRIPTION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"WEST_LIMIT_LENGTHCHAR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SOUTH_LIMIT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SOUTH_LIMIT_DESCRIPTION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SOUTH_LIMIT_LENGTHCHAR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;