
  CREATE TABLE "MOBASHER"."REGA_LOCATIONS" 
   (	"ID" NUMBER, 
	"STREET" VARCHAR2(255) COLLATE "USING_NLS_COMP" DEFAULT NULL, 
	"POSTAL_CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP" DEFAULT NULL, 
	"BUILDING_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP" DEFAULT NULL, 
	"ADDITIONAL_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP" DEFAULT NULL, 
	"LONGITUDE" VARCHAR2(255) COLLATE "USING_NLS_COMP" DEFAULT NULL, 
	"LATITUDE" VARCHAR2(255) COLLATE "USING_NLS_COMP" DEFAULT NULL, 
	"REGION_ID" NUMBER, 
	"CITY_ID" NUMBER, 
	"DISTRICT_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;