
  CREATE TABLE "MOBASHER"."REGA_ADVERTISERS" 
   (	"ID" NUMBER, 
	"ADVERTISER_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ADVERTISER_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PHONE_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AD_LICENSE_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BROKERAGE_AND_MARKETING_LICENSE_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"REGA_ADVERTISEMENT_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;