
  CREATE TABLE "MOBASHER"."SELLERS_CONTRACTS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER NOT NULL DISABLE, 
	"REQUEST_DETAILS_ID" NUMBER, 
	"CONTRACT_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CONTRACT_START_DATE" DATE, 
	"CONTRACT_END_DATE" DATE, 
	"CONTRACT_STATUS" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "SELLES_CONTRACTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLES_CONTRACTS_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;