
  CREATE TABLE "MOBASHER"."SELLER_ASSIGNED_FILES" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"CITY_ID" NUMBER, 
	"FILE_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER, 
	"IS_DISPLAYED" NUMBER, 
	"NOTES" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "SELLER_ASSIGNED_FILES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_ASSIGNED_FILES_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "SELLER_ASSIGNED_FILES_CITY_FK" FOREIGN KEY ("CITY_ID")
	  REFERENCES "MOBASHER"."CITIES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;