
  CREATE TABLE "MOBASHER"."SELLER_WALLETS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"TYPE_ID" NUMBER, 
	"TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TOTAL_PRICE" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLER_WALLETS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_WALLETS_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;