
  CREATE TABLE "MOBASHER"."SELLER_CATEGORIES" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLER_CATEGORIES_UNQ" UNIQUE ("SELLER_ID", "CATEGORY_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_CATEGORIES_SELLER_IS_NOT_NULL" CHECK ( "SELLER_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SELLER_CATEGORIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_CATEGORIES_CATEGORY_IS_NOT_NULL" CHECK ( "CATEGORY_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SELLER_CATEGORIES_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;