
  CREATE TABLE "MOBASHER"."SELLER_DEPARTMENTS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"COUNTRY_CALL_KEY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_PUBLIC" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLER_DEPARTMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_DEPARTMENTS_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;