
  CREATE TABLE "MOBASHER"."SELLERS_REQUESTS_DETAILS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER NOT NULL ENABLE, 
	"APPLICANT_NAME" VARCHAR2(128) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"APPLICANT_PHONE_NUMBER" VARCHAR2(128) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"APPLICANT_EMAIL" VARCHAR2(128) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"APPLICANT_TYPE_ID" NUMBER, 
	"APPLICANT_ID_URL" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"APPLICANT_AUTHORIZATION_URL" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"CR_URL" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"NATIONAL_ADDRESS_URL" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"LOGO_URL" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"TAX_URL" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"ADMIN_ID_URL" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"ADMIN_AUTHORIZATION_URL" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"IBAN_URL" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"IS_EDITABLE" NUMBER DEFAULT 0, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PORTABLE_CONTRACT_URL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"REAL_ESTATE_CONTRACT_URL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SELLER_REAL_ESTATE_CONTRACT_URL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SELLER_PORTABLE_CONTRACT_URL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_EDITABLE_REALESTATE_CONTRACT" NUMBER DEFAULT 0, 
	"IS_EDITABLE_PORTABLE_CONTRACT" NUMBER DEFAULT 0, 
	"IS_EDITABLE_CONTRACT" NUMBER DEFAULT 0, 
	"PORTABLE_CONFIRMATION" NUMBER DEFAULT 0, 
	"REALESTATE_CONFIRMATION" NUMBER DEFAULT 0, 
	"PORTABLE_CONTRACT_NOTES" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"PORTABLE_CONTRACT_SCOPE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"PORTABLE_MOBASHER_OBLIGATIONS" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "SELLERS_REQUESTS_DETAILS_EMAIL" UNIQUE ("APPLICANT_EMAIL")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLERS_REQUESTS_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLERS_REQUESTS_DETAILS_PHONE_UNQ" UNIQUE ("APPLICANT_PHONE_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "APP_TYPE_FK" FOREIGN KEY ("APPLICANT_TYPE_ID")
	  REFERENCES "MOBASHER"."LOOKUP_DETAIL" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "SELLERS_REQUESTS_DETAILS_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ON DELETE CASCADE ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;