
  CREATE TABLE "MOBASHER"."SELLERS_COMMENTS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"COMMENT_TEXT" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLERS_COMMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;