
  CREATE TABLE "MOBASHER"."SELLER_ASSIGNED_FILES_MASTER" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CITY_ID" NUMBER, 
	"SEQUENCE" NUMBER, 
	"NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STATUS_ID" NUMBER, 
	"STICKERS_FILE_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"FILE_ID" NUMBER, 
	"CHECKER_USER_ID" NUMBER, 
	"AGENT_PHOTOGRAPHY_PAYMENT_DOCUMENT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PHOTOGRAPHY_PAYMENT_DOCUMENT" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"AGENT_INSPECTION_PAYMENT_DOCUMENT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"INSPECTION_PAYMENT_DOCUMENT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP" DEFAULT 'EXCEL_SHEET', 
	"PHOTOGRAPHY_TRANSFERRED_AMOUNT" NUMBER, 
	"INSPECTION_TRANSFERRED_AMOUNT" NUMBER, 
	 CONSTRAINT "SELLER_ASSIGNED_FILES_MASTER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_ASSIGNED_FILES_MASTER_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOBASHER"."APP_USERS" ("ID") ENABLE, 
	 CONSTRAINT "SELLER_ASSIGNED_FILES_MASTER_FILE_FK" FOREIGN KEY ("FILE_ID")
	  REFERENCES "MOBASHER"."SELLER_ASSIGNED_FILES" ("ID") ENABLE, 
	 CONSTRAINT "SELLER_ASSIGNED_FILES_MASTER_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "SELLER_ASSIGNED_FILES_MASTER_CITY_FK" FOREIGN KEY ("CITY_ID")
	  REFERENCES "MOBASHER"."CITIES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;