
  CREATE TABLE "MOBASHER"."SELLER_ROLE_GROUPS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"GROUP_NAME" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"GROUP_DESCRIPTION" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"SELLER_ID" NUMBER, 
	 CONSTRAINT "APP_ROLE_GROUPS_SELLER_NN" CHECK ( "SELLER_ID" IS NOT NULL ) ENABLE, 
	 CONSTRAINT "APP_RGP_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "APP_ROLE_GROUPS_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;