
  CREATE TABLE "MOBASHER"."SELLER_CITIES" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"CITY_ID" NUMBER, 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLER_CITIES_UNQ" UNIQUE ("SELLER_ID", "CITY_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_CITIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_CITIES_CITY_NOT_NULL" CHECK ( "CITY_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SELLER_CITIES_NOT_NULL" CHECK ( "SELLER_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SELLER_CITIES_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "SELLER_CITIES_CITY_FK" FOREIGN KEY ("CITY_ID")
	  REFERENCES "MOBASHER"."CITIES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;