
  CREATE TABLE "MOBASHER"."SELLER_NOTIFICATIONS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"TYPE_ID" NUMBER, 
	"MESSAGE_AR" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"MESSAGE_EN" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"IS_SEEN" NUMBER DEFAULT 0, 
	"IS_CANCELED" NUMBER DEFAULT 0, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLER_NOTIFICATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_NOTIFICATIONS_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;