
  CREATE TABLE "MOBASHER"."SELLERS_REQUESTS_CONTRACTS_TEMP" 
   (	"ID" NUMBER, 
	"REQUEST_DETAILS_ID" NUMBER, 
	"DEPENDINCES_TYPE" NUMBER, 
	"COMMISSION_TYPE" NUMBER, 
	"AUCTION_COMMISSION" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SOLD_PRODUCT_COMMISSION" NUMBER, 
	"TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AUCTION_TYPE" NUMBER, 
	"LIMIT_COMMISSION" NUMBER, 
	"CONTRACT_ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	 CONSTRAINT "SELLERS_REQUESTS_CONTRACTS_TEMP_CON_CK" CHECK ( "REQUEST_DETAILS_ID" IS NOT NULL  ) DISABLE, 
	 CONSTRAINT "SELLERS_REQUESTS_CONTRACTS_TEMP_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLERS_REQUESTS_CONTRACTS_TEMP_CON_FK" FOREIGN KEY ("REQUEST_DETAILS_ID")
	  REFERENCES "MOBASHER"."SELLERS_REQUESTS_DETAILS" ("ID") DISABLE, 
	 CONSTRAINT "SELLERS_REQUESTS_CONTRACTS_TEMP_CON_FK2" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "SELLERS_REQUESTS_CONTRACTS_TEMP_CON_FK1" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "MOBASHER"."SELLERS_CONTRACTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;