
  CREATE TABLE "MOBASHER"."SELLER_BANK_TRANSFERS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"BUYER_BANK_ACCOUNT_ID" NUMBER, 
	"SELLER_BANK_ACCOUNT_ID" NUMBER, 
	"MONEY_MOVEMENT_TYPE" VARCHAR2(3) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TRANSFER_DATE" DATE NOT NULL ENABLE, 
	"TOTAL_PRICE" NUMBER NOT NULL ENABLE, 
	"IS_ARRIVED" NUMBER DEFAULT 0, 
	"IS_REFUNDED" NUMBER DEFAULT 0, 
	"REFUND_DATE" DATE, 
	"NOTES" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"RECEIPT_IMAGE_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"AUCTIONS_GATE_BANK_ACCOUNT" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLER_BANK_TRANSFERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_BANK_TRANSFERS_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "SELLER_BANK_TRANSFERS_BUYER_BANK_ACCOUNT_FK" FOREIGN KEY ("BUYER_BANK_ACCOUNT_ID")
	  REFERENCES "MOBASHER"."BUYER_BANK_ACCOUNTS" ("ID") DISABLE, 
	 CONSTRAINT "SELLER_BANK_TRANSFERS_SELLER_BANK_ACCOUNT_FK" FOREIGN KEY ("SELLER_BANK_ACCOUNT_ID")
	  REFERENCES "MOBASHER"."SELLER_BANK_ACCOUNTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;