
  CREATE TABLE "MOBASHER"."SELLER_INVOICES" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"SELLER_BANK_TRANSFER_ID" NUMBER, 
	"AUCTION_GATE_BANK_TRANSFER_ID" NUMBER, 
	"SELLER_WALLET_ID" NUMBER, 
	"CURRENCY_ID" NUMBER, 
	"KEY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"INVOICE_TYPE_ID" NUMBER, 
	"PAYMENT_TYPE_ID" NUMBER, 
	"PAYMENT_STATUS_ID" NUMBER, 
	"TAX_PERCENTAGE" NUMBER, 
	"ADDITIONS" NUMBER, 
	"SUB_TOTAL" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLER_INVOICES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_INVOICES_SELLER_WALLET_FK" FOREIGN KEY ("SELLER_WALLET_ID")
	  REFERENCES "MOBASHER"."SELLER_WALLETS" ("ID") ENABLE, 
	 CONSTRAINT "SELLER_INVOICES_SELLER_BANK_TRANSFERS_FK" FOREIGN KEY ("SELLER_BANK_TRANSFER_ID")
	  REFERENCES "MOBASHER"."SELLER_BANK_TRANSFERS" ("ID") ENABLE, 
	 CONSTRAINT "SELLER_INVOICES_SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "SELLER_INVOICES_AUCTION_GATE_BANK_TRANSFER_FK" FOREIGN KEY ("AUCTION_GATE_BANK_TRANSFER_ID")
	  REFERENCES "MOBASHER"."AUCTION_GATE_BANK_TRANSFERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;