
  CREATE TABLE "MOBASHER"."SELLERS_REQUESTS_CONTRACTS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER NOT NULL DISABLE, 
	"REQUEST_DETAILS_ID" NUMBER NOT NULL DISABLE, 
	"DEPENDINCES_TYPE" NUMBER, 
	"COMMISSION_TYPE" NUMBER, 
	"AUCTION_COMMISSION" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SOLD_PRODUCT_COMMISSION" NUMBER, 
	"TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AUCTION_TYPE" NUMBER, 
	"LIMIT_COMMISSION" NUMBER, 
	"CONTRACT_ID" NUMBER, 
	 CONSTRAINT "SELLES_REQUESTS_CONTRACTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLES_REQUESTS_CONTRACTS_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE, 
	 CONSTRAINT "SELLES_REQUESTS_CONTRACTS_FK2" FOREIGN KEY ("REQUEST_DETAILS_ID")
	  REFERENCES "MOBASHER"."SELLERS_REQUESTS_CONTRACTS" ("ID") DISABLE, 
	 CONSTRAINT "SELLES_REQUESTS_CONTRACTS_FK3" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "MOBASHER"."SELLERS_CONTRACTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;