
  CREATE TABLE "MOBASHER"."SELLER_ROLE_GROUP_USERS" 
   (	"ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"GROUP_ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLER_ROLE_GROUP_USERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;