
  CREATE TABLE "MOBASHER"."SELLER_RATING" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"RATE" NUMBER, 
	"RATING_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SELLER_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;