
  CREATE TABLE "MOBASHER"."SELLER_QUESTIONNAIRE" 
   (	"ID" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"AUCTION_TYPE_ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ADMIN_PHONE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SALES_VALUE" NUMBER, 
	"NOTES_AR" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"NOTES_EN" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"COUNTRY_CALL_KEY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FIRST_YEAR" NUMBER, 
	"SECOND_YEAR" NUMBER, 
	"THIRD_YEAR" NUMBER, 
	"FEES_PERCENTAGE" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "SELLER_QUESTIONNAIRE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;