
  CREATE TABLE "MOBASHER"."SELLERS_WALLETS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SELLER_ID" NUMBER NOT NULL ENABLE, 
	"AUCTION_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"CONTRACT_ID" NUMBER, 
	"AMMOUNT" NUMBER NOT NULL ENABLE, 
	"ADD_BALANCE_TYPE" NUMBER NOT NULL ENABLE, 
	"ADD_BALANCE_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"RECEIPT_NO" VARCHAR2(300) COLLATE "USING_NLS_COMP", 
	"RECEIPT_URL" VARCHAR2(300) COLLATE "USING_NLS_COMP", 
	"DESC_AR" VARCHAR2(300) COLLATE "USING_NLS_COMP", 
	"DESC_EN" VARCHAR2(300) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PAYMENT_STATUS" NUMBER, 
	"REFERENCE_RECEIPT_NO" VARCHAR2(150) COLLATE "USING_NLS_COMP", 
	"PARTIAL_AMMOUNT" NUMBER DEFAULT 0, 
	 CONSTRAINT "SELLERS_WALLETS_CON1" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MOBASHER"."SELLERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "MOBASHER"."SELLERS_WALLETS_PK" ON "MOBASHER"."SELLERS_WALLETS" ("ID") 
  ;
ALTER TABLE "MOBASHER"."SELLERS_WALLETS" ADD CONSTRAINT "SELLERS_WALLETS_PK" PRIMARY KEY ("ID")
  USING INDEX "MOBASHER"."SELLERS_WALLETS_PK"  ENABLE;