
  CREATE TABLE "MOBASHER"."SELLER_BANK_ACCOUNTS" 
   (	"ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"BANK_ID" NUMBER, 
	"CURRENCY_ID" NUMBER, 
	"ACCOUNT_NO" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"IBAN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_OWNER" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"BANK_CARD_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"IS_VERIFIED" NUMBER, 
	"IS_AGREE" NUMBER DEFAULT 0, 
	 CONSTRAINT "SELLER_BANK_ACCOUNTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;