
  CREATE TABLE "MOBASHER"."SERVICES_AGENT_REQUESTS" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"AGENT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"VIN_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PLATE_NUMBER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"YEAR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BUYER_NID_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"SELLER_FORM_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"SELLER_WAIVER_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"SELLER_DELEGATION_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IMAGE_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"AGENT_DOCUMENT_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "SERVICES_AGENT_REQUESTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;