
  CREATE TABLE "MOBASHER"."SMS_LOGS" 
   (	"ID" NUMBER, 
	"PHONE_NUMBER" NUMBER, 
	"MESSAGE" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"IS_SEND" NUMBER, 
	"TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"IS_RESEND" NUMBER DEFAULT 0, 
	"RESEND_COUNT" NUMBER DEFAULT 0, 
	 CONSTRAINT "SMS_LOGS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;