
  CREATE TABLE "MOBASHER"."SUB_CATEGORIES" 
   (	"ID" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IMAGE_URL" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"SEQ" NUMBER, 
	"IS_INDIVIDUAL" NUMBER DEFAULT 0, 
	 CONSTRAINT "SUB_CATEGORIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SUB_CATEGORIES_FK" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "MOBASHER"."CATEGORIES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;