
  CREATE TABLE "MOBASHER"."SYS_LOG_HISTORY" 
   (	"APP_ID" NUMBER, 
	"LOG_HISTORY_ID" NUMBER NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"COLUMN_NMAE" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"OLD_VALUE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"NEW_VALUE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"ROW_ID" NUMBER, 
	"COLUMN_COMMENTS" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"OTHER1" NUMBER, 
	"OTHER2" NUMBER, 
	"OTHER3" NUMBER, 
	"OTHER4" NUMBER, 
	"OTHER5" NUMBER, 
	"OTHER6" NUMBER, 
	"OTHER7" NUMBER, 
	"OTHER8" NUMBER, 
	"OTHER9" NUMBER, 
	"OTHER10" NUMBER, 
	"REMARKS" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"REGDATE" DATE DEFAULT sysdate, 
	"REGUSER" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"REGCOMPUTERIP" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"CANCELDATE" DATE, 
	"CANCELUSER" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"CANCELCOMPUTERIP" VARCHAR2(100) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "MOBASHER"."SYS_LOG_HISTORY_PK" ON "MOBASHER"."SYS_LOG_HISTORY" ("LOG_HISTORY_ID") 
  ;
ALTER TABLE "MOBASHER"."SYS_LOG_HISTORY" ADD CONSTRAINT "SYS_LOG_HISTORY_PK" PRIMARY KEY ("LOG_HISTORY_ID")
  USING INDEX "MOBASHER"."SYS_LOG_HISTORY_PK"  ENABLE;