
  CREATE TABLE "MOBASHER"."TEMP_UPLOADED_FILES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EXT" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"MIME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SIZE_" NUMBER, 
	"URL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PROVIDER" VARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;