
  CREATE TABLE "MOBASHER"."TEMP_UPLOADED_FILES_MORPH" 
   (	"ID" NUMBER, 
	"UPLOAD_FILE_ID" NUMBER, 
	"RELATED_ID" NUMBER, 
	"RELATED_TYPE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"FIELD" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ORDER_" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;