
  CREATE TABLE "MOBASHER"."TICKET_CHAT" 
   (	"ID" NUMBER, 
	"TICKET_ID" NUMBER, 
	"TEXT" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "TICKET_CHAT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TICKET_CHAT_FK" FOREIGN KEY ("TICKET_ID")
	  REFERENCES "MOBASHER"."TICKETS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;