
  CREATE TABLE "MOBASHER"."TICKET_ATTACHMENTS" 
   (	"ID" NUMBER, 
	"TICKET_ID" NUMBER, 
	"URL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"FILE_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "TICKET_ATTACHMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;