
  CREATE TABLE "MOBASHER"."TICKETS" 
   (	"ID" NUMBER, 
	"BUYER_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BUYER_EMAIL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BUYER_PHONE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TITLE" VARCHAR2(400) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"TYPE" NUMBER, 
	"STATUS" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"BUYER_ID" NUMBER NOT NULL DISABLE, 
	"DEPARTMENT_ID" NUMBER, 
	"BUYER_NATIONAL_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "TICKETS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TICKETS_FK" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "MOBASHER"."MOBASHER_DEPARTMENTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;