
  CREATE TABLE "MOBASHER"."TRANSPORTATION_USERS" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IDENTITY_NUMBER" NUMBER, 
	"PHONE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_REGISTERED" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EMAIL" NUMBER, 
	 CONSTRAINT "TRANSPORTATION_USERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TRANSPORTATION_USERS_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOBASHER"."APP_USERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;