
  CREATE TABLE "MOBASHER"."TRANSPORTATION_REQUEST_DOCUMENTS" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"DOCUMENT_NAME" VARCHAR2(2555) COLLATE "USING_NLS_COMP", 
	"DOCUMENT_URL" VARCHAR2(2555) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TYPE" NUMBER, 
	 CONSTRAINT "TRANSPORTATION_REQUEST_DOCUMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TRANSPORTATION_REQUEST_DOCUMENTS_FK" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "MOBASHER"."TRANSPORTATION_REQUESTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;