
  CREATE TABLE "MOBASHER"."TRANSPORTATION_AGENT_DETAILS" 
   (	"ID" NUMBER, 
	"AGENT_ID" NUMBER, 
	"INSURANCE_TYPE" NUMBER, 
	"TRUCK_TYPE" NUMBER, 
	"OPERATION_NO" VARCHAR2(2555) COLLATE "USING_NLS_COMP", 
	"OPERATION_CARD" VARCHAR2(2555) COLLATE "USING_NLS_COMP", 
	"REGISTRATION_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "TRANSPORTATION_AGENT_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TRANSPORTATION_AGENT_DETAILS_FK" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "MOBASHER"."AGENTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;