
  CREATE TABLE "MOBASHER"."TRANSPORTATION_REQUEST_PRICING" 
   (	"ID" NUMBER, 
	"AGENT_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"TOWING_TRUCK_TYPE" NUMBER, 
	"TOWING_TRUCK_URL" VARCHAR2(2500) COLLATE "USING_NLS_COMP", 
	"OFFERED_PRICE" NUMBER, 
	"IS_APPROVED" NUMBER DEFAULT 0, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_WITHDRAWAL" NUMBER DEFAULT 0, 
	"IS_SELECTED" NUMBER DEFAULT 0, 
	"TARGET_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"TRACK_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PAY_ID" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TRAN_ID" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"PAY_RESULT" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"RESPONSE_HASH" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"IS_PAID" NUMBER DEFAULT 0, 
	 CONSTRAINT "TRANSPORTATION_REQUEST_PRICING_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TRANSPORTATION_REQUEST_PRICING_REQUEST_FK" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "MOBASHER"."TRANSPORTATION_REQUESTS" ("ID") ENABLE, 
	 CONSTRAINT "TRANSPORTATION_REQUEST_PRICING_AGENT_FK" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "MOBASHER"."AGENTS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;