
  CREATE TABLE "MOBASHER"."URLS_HISTORY" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"URL_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"OBJECT_ID" NUMBER, 
	"ORIGINAL_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"UPDATED_URL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "URLS_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;