
  CREATE TABLE "MOBASHER"."VEHICLE_MODEL" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"VEHICLE_MAKE_ID" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "VEHICLE_MODEL_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VEHICLE_MODEL_MAKE_FK" FOREIGN KEY ("VEHICLE_MAKE_ID")
	  REFERENCES "MOBASHER"."VEHICLE_MAKE" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;