
  CREATE TABLE "MOBASHER"."VEHICLE_EXTERNAL_COLOR" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "VEHICLE_EXTERNAL_COLOR_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;