
  CREATE TABLE "MOBASHER"."VEHICLE_CLASS" 
   (	"ID" NUMBER, 
	"NAME_AR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAME_EN" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"VEHICLE_MODEL_ID" NUMBER, 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "VEHICLE_CLASS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VEHICLE_CLASS_MODEL_FK" FOREIGN KEY ("VEHICLE_MODEL_ID")
	  REFERENCES "MOBASHER"."VEHICLE_MODEL" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;