
  CREATE TABLE "MOBASHER"."VEHICLES" 
   (	"ID" NUMBER, 
	"INFATH_REPORT_ID" NUMBER, 
	"SEQ" NUMBER, 
	"VEHICLE_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PLATE_NUMBER" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"VEHICLE_SEQUENCE" NUMBER, 
	"MANUFACTURING_YEAR" NUMBER, 
	"VEHICLE_PULL" NUMBER, 
	"STATUS" NUMBER, 
	"NOTES" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	"CITY_ID" NUMBER, 
	"REFUSER_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"REFUSER_IDENTITY_NO" NUMBER, 
	"REFUSER_PHONE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"ENTITY_TYPE" NUMBER, 
	"ENTITY_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"UNABLE_WITHDRAW_REASON" NUMBER, 
	"ATTACHED_URL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	 CONSTRAINT "VEHICLES_UNQ" UNIQUE ("VEHICLE_SEQUENCE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VEHICLES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "VEHICLES_NOT_NULL" CHECK ( "INFATH_REPORT_ID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "VEHICLES_FK" FOREIGN KEY ("INFATH_REPORT_ID")
	  REFERENCES "MOBASHER"."INFATH_DECISION" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;