
  CREATE TABLE "MOBASHER"."WALLETS" 
   (	"ID" NUMBER, 
	"BUYER_ID" NUMBER, 
	"AUCTION_ID" NUMBER, 
	"AUCTION_TYPE_ID" NUMBER, 
	"MONEY_MOVMENT_TYPE_ID" NUMBER, 
	"INSURANCE_TYPE_ID" NUMBER, 
	"USER_FOR_ID" NUMBER, 
	"PARTICIPANT_AS_ID" NUMBER, 
	"ADDITIONS" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"CURRENT_BALANCE" NUMBER, 
	"NOTES_AR" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"NOTES_EN" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"AGENT_DOCUMENT_URL" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER DEFAULT 1, 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "WALLETS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "WALLETS_BUYER_FK" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "MOBASHER"."BUYERS" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;